### ISSUE TITLE
Peer2Peer Review

### ISSUE THREAD

**Issue by olawalecoder** [mugishasam123/first-capstone-project#2]
You have a clean code. 👍 and an amazing website 💯 .
Here are some observations:
- I noticed the speaker sections do not have paddings or margins, it will be nice if it has.
- And I also observed that some of the logos are stretched.

**Comment by VSeray** [comment]
Great job finishing your project and coming this far 👏 
 Here are some of my observations:

- I think it would have been nice if in your mobile version the more button would be functional, since you have added it in your design.

Other than that well done 🎉

**Comment by gtekle** [comment]
Well done! You have done a great job! 
The layout is really good. 
Here are few points, that I believe would be good if you look at them.
1. On the readMe file, it would be good if you edit the author and the acknowledgement to the original designer.
2. On the main program section, whenever you hover on each program the page moves vertically. I think that issue can be avoided if you use `outline` instead of `border` for the hover effect.
3. In the java script file, it would be good if more descriptive variable names and file names are used according to the best practice.

**Comment by mugishasam123** [comment]
sure i worked on issues stated 
and thanks for helping me make my codebase clean
